# -*- coding: utf-8 -*-
"""PetrackProject2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/193X98BDO_Byt01DIGKKv1utFEd4WEylf

Academic Performance Analysis of Computer Science Students.

Dataset overview:
This dataset contains demographics, behavioral, and academic performance information for Computer Science students. Variables contain academic metrics, study behaviors, and background characteristics.

Understanding which factors most strongly influence academic success can provide useful insight for advising, curriculum planning, and student support.

This project's aim is to:
Perform exploratory data analysis to identify patterns in student performance.
Engineer relevant features for modeling.
Building a classification model to predict high-performing students.
Interpret model outputs to identify key performance drivers.

Takeaway: By identifying the strongest predictors of academic success, institutions can better implement strategies and evidence based learning interventions to improve student outcomes.

This dataset came from kaggle.com and the data was created by Aleesha Nadeem
https://www.kaggle.com/datasets/nalisha/computer-science-students-performance
"""

from google.colab import files
uploaded = files.upload()

#If you are running this locally, remove the Google Colab file insert and instead enter df = pd.read_csv("cs_studemts.csv")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    roc_curve,
    auc
)

plt.style.use("seaborn-v0_8")
sns.set_context("talk")

df = pd.read_csv("cs_students.csv")

print("Dataset Shape:", df.shape)
df.head()

"""After loading in the dataset, I am going to do the inital data inspection.

Before I can model, I have to examine the data:
Data types
Missing or null values
Basic statistics
"""

df.info()
df.describe()

#We begin analyzing the distribution of academic performance and relationships between numeric variables.

#The first model is going to show GPA Distribution

plt.figure(figsize=(8,5))
sns.histplot(df["GPA"], bins=20)
plt.title("Distribution of GPA")
plt.xlabel("GPA")
plt.ylabel("Number of Students")
plt.tight_layout()
plt.show()

#This next model is a corrrelation heatmap
plt.figure(figsize=(10,8))
sns.heatmap(
    df.corr(numeric_only=True),
    annot=True,
    cmap="coolwarm",
    fmt=".2f"
)
plt.title("Correlation Heatmap")
plt.tight_layout()
plt.show()

"""In this section I am going to be building a classification model. To create this, I will be using binary values of 0 and 1.

High Performance = 1
Low Performance  = 0

Students will be classified based on whether their GPA is above or below the median.
"""

df["High_Performer"] = np.where(
    df["GPA"] >= df["GPA"].median(),
    1,
    0
)

df["High_Performer"].value_counts()

le = LabelEncoder()

for col in df.select_dtypes(include="object").columns:
    df[col] = le.fit_transform(df[col])

X = df.drop(["High_Performer", "GPA"], axis=1)
y = df["High_Performer"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training Set Size:", X_train.shape)
print("Testing Set Size:", X_test.shape)

model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Accuracy:", round(accuracy_score(y_test, y_pred), 3))
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

"""In this next code block I will create a confusion matrix.
This is important to test actual vs. predicted values.
"""

cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues")
plt.title("Confusion Matrix")
plt.xlabel("Predicted Label")
plt.ylabel("True Label")
plt.tight_layout()
plt.show()

"""The code box below, explains where students will demonstrate their importantce to a hiring manager."""

importances = pd.Series(
    model.feature_importances_,
    index=X.columns
)

plt.figure(figsize=(8,6))
importances.sort_values().plot(kind="barh")
plt.title("Feature Importance")
plt.xlabel("Importance Score")
plt.tight_layout()
plt.show()

y_prob = model.predict_proba(X_test)[:,1]

fpr, tpr, _ = roc_curve(y_test, y_prob)
roc_auc = auc(fpr, tpr)

plt.figure(figsize=(6,5))
plt.plot(fpr, tpr, label=f"AUC = {roc_auc:.2f}")
plt.plot([0,1], [0,1], linestyle="--")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve")
plt.legend()
plt.tight_layout()
plt.show()

"""The last two code blocks are for modeling and validation"""

from sklearn.linear_model import LogisticRegression

log_model = LogisticRegression(max_iter=1000)
log_model.fit(X_train, y_train)

log_pred = log_model.predict(X_test)

print("Logistic Accuracy:", accuracy_score(y_test, log_pred))

from sklearn.model_selection import cross_val_score

cv_scores = cross_val_score(model, X, y, cv=5)

print("Cross-validation scores:", cv_scores)
print("Average CV score:", cv_scores.mean())

"""Conclusion:
The Random Forest model demonstrated strong predictive capability in classifying high-performing students. Feature importance analysis revealed which academic and behavioral factors most strongly influence student performance.

These findings suggest that targeted academic interventions focusing on high-impact variables may significantly improve overall student success rates.

"""